[build]
  functions = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { User-Agent = "facebookexternalhit" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { User-Agent = "Instagram" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { User-Agent = "Twitterbot" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { User-Agent = "Discordbot" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { User-Agent = "TikTok" }
